### PR TITLE
fix: viewstart may not be sent if monitor attached while idle && playWhenReady == true

### LINKED ISSUE #36: viewstart being delayed in live video unit first ad
start live video, 'viewstart' delayed unit 'adbreakstart'
image
image

This issue can be reproduced 100%,Open Live video -> video playing -> ad play-> video...
I uploaded the image, **actually live video has played 20s**, but 'VIEWER TIMELINE' is not right.
I think the 'viewstart' event should be with playing in PLAYHEAD TIME 00:00.
By any chance, do you have any ideas or tips which could help us to identify the issue?
Thanks.

Test device: Android 8
Mux sdk: `com.mux.stats.sdk.muxstats:data-media3:0.7.4, 0.8.0`

### PR DESCRIPTION
**Pull request by daytime-em**
This should fix #36.

Depends on muxinc/stats-sdk-android#48

### CODE REVIEW

File: library-exo/src/main/java/com/mux/stats/sdk/muxstats/ExoPlayerBinding.kt [hunk 1]
```diff
@@ -43,6 +43,8 @@ open class ExoPlayerBinding : MuxPlayerAdapter.PlayerBinding<ExoPlayer> {
   override fun bindPlayer(player: ExoPlayer, collector: MuxStateCollector) {
     catchUpPlayState(player, collector)
 
+    player.stop()
```
Comment (daytime-em) [inline library-exo/src/main/java/com/mux/stats/sdk/muxstats/ExoPlayerBinding.kt:46]: This is wrong don't merge this !!

File: library-exo/src/main/java/com/mux/stats/sdk/muxstats/ExoPlayerBinding.kt [hunk 2]
```diff
@@ -79,10 +79,12 @@ open class ExoPlayerBinding : MuxPlayerAdapter.PlayerBinding<ExoPlayer> {
     if (player.playWhenReady) {
       // Captures auto-play & late-registration, setting state and sending 'viewstart'
       collector.play()
-    } else {
-      collector.pause()
     }
-    collector.handleExoPlaybackState(player.playbackState, player.playWhenReady)
+    // The player will be idle when we are first attached, so we don't need to say we paused
+    //  (which is how IDLE is handled during actual playback)
+    if (player.playbackState != Player.STATE_IDLE) {
```
Comment (andrewjl-mux) [inline library-exo/src/main/java/com/mux/stats/sdk/muxstats/ExoPlayerBinding.kt:85]: Is this worth adding a test for?

**Review by andrewjl-mux — APPROVED** [review]

File: library-exo/src/main/java/com/mux/stats/sdk/muxstats/ExoPlayerBinding.kt (hunk 2 above)
Comment (daytime-em) [reply library-exo/src/main/java/com/mux/stats/sdk/muxstats/ExoPlayerBinding.kt:85]: 🤔 That seems reasonable

Comment (daytime-em) [reply library-exo/src/main/java/com/mux/stats/sdk/muxstats/ExoPlayerBinding.kt:85]: I looked into this, but I think it would be better as an integration test. We have a "classical" kind of misusage test I need to port over that will handle this.

Comment (andrewjl-mux) [reply library-exo/src/main/java/com/mux/stats/sdk/muxstats/ExoPlayerBinding.kt:85]: 💯
